return {
    REQUEST_CONNECT = 1,
    CONNECT = 2,

    PLAYER_INPUT = 3,
    PLAYER_CHAT = 4,

    NOTIFICATION = 5,

    TERRAIN = 6,

    ENTITY_DESTROY = 7,
    ENTITY_UPDATE = 8,

    BULLET_CREATE = 9,
    CRATE_CREATE = 10,
    EXPLOSION_CREATE = 11,
    ROVER_CREATE = 12,

    NAME_CHANGE = 13,
}